# Change these first
owner: inprod # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: InProd Website
    url: https://www.inprod.io
  - name: InProd DEV
    url: https://dev.inprod.io
  - name: InProd PROD
    url: https://red.au.inprod.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/inprod/upptime/refs/heads/master/assets/inprod-logo.png
  favicon: https://raw.githubusercontent.com/inprod/upptime/refs/heads/master/assets/inprod-logo.png
  name: InProd
  introTitle: "**InProd Upptime**"
  introMessage: This page tracks the uptime of InProd's website and application. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
